### ISSUE TITLE
might be useful to set the website in the project description 

### ISSUE THREAD

**Issue by tbates** [WeAreVisualizers/wearevisualizers.github.io#1]
hi, stumbled on this from your DiagrammeR package (thank you so much for that package - SOOOO much easier than trying to get users to install graphviz!).

Might help discovery for this package to set the website field to wearevisualizers.github.io

(and make that a link in the readme  [wearevisualizers.github.io](http://visualizers.co)

**Comment by rich-iannone** [comment]
@tbates Good idea! I've been meaning to do more with the website and make it more than just a placeholder. (And thanks for the good words!)
